name: CI

on:
  push:
  schedule:
  - cron: '0 23 * * *'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: Gr1N/setup-poetry@v7
    - if: matrix.python-version == '3.11' && matrix.os == 'macos-latest'
      run: mkdir ~/.local/bin && ln -s ~/Library/Python/3.11/bin/poetry ~/.local/bin/poetry
    - run: poetry --version
    - run: poetry install
    - run: poetry run pytest

  test-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./run-docker-test.sh
